# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

SQ_VERSION: 
  - DEV
  - LATEST_RELEASE[6.7]

JENKINS_VERSION:
# Oldest LTS that still have its update center maintained
  - 2.107.3
# More recent LTS
  - 2.164.1

exclude:
  - SQ_VERSION: LATEST_RELEASE[6.7]
    JENKINS_VERSION: 2.164.1
  - SQ_VERSION: LATEST_RELEASE[6.7]
    JENKINS_VERSION: 2.107.3
    SLAVE: windows
  - SQ_VERSION: DEV
    JENKINS_VERSION: 2.107.3
  - SQ_VERSION: DEV
    JENKINS_VERSION: 2.164.1
    SLAVE: windows
  
